# Generated by Django 5.0.14 on 2025-11-18 23:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="attachment",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="raw"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="proposal_attachment",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="raw"
            ),
        ),
    ]
