# Generated by Django 5.0.14 on 2025-11-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_job_attachment_profile_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="jobs/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="proposal_attachment",
            field=models.FileField(blank=True, null=True, upload_to="proposals/"),
        ),
    ]
